export const dataDevices = [
  {
    id: 0,
    name: "Apple iPhone 12",
    image: require("../images/apple_12.png"),
    year: "2020",
    made: "Китай",
    brand: "Apple",
    nfc: false,
    eSim: true,
    price: "81 990 ₽",
    gz: "60 Гц",
    diagonal: "6,1",
    wirelessСharging: true,
    memory: "128 Гб",
  },
  {
    id: 1,
    name: "Apple iPhone XR",
    image: require("../images/apple_xr.png"),
    year: "2018",
    made: "Китай",
    brand: "Apple",
    nfc: true,
    eSim: true,
    price: "47 999 ₽",
    gz: "60 Гц",
    diagonal: "6,1",
    wirelessСharging: true,
    memory: "128 Гб",
  },
  {
    id: 2,
    name: "Xiaomi Mi 11 Lite",
    image: require("../images/xiaomi.png"),
    year: "2021",
    made: "Китай",
    brand: "Xiaomi",
    nfc: true,
    eSim: true,
    price: "27 490 ₽",
    gz: "90 Гц",
    diagonal: "6,55",
    wirelessСharging: false,
    memory: "128 Гб",
  },
  {
    id: 3,
    name: "Samsung Galaxy A72",
    image: require("../images/a72.png"),
    year: "2020",
    made: "Вьетнам",
    brand: "Samsung",
    nfc: true,
    eSim: false,
    price: "32 890 ₽",
    gz: "90 Гц",
    diagonal: "6,7",
    wirelessСharging: true,
    memory: "128 Гб",
  },
  {
    id: 4,
    name: "Samsung Galaxy S21",
    image: require("../images/s21.png"),
    year: "2021",
    made: "Китай",
    brand: "Samsung",
    nfc: true,
    eSim: true,
    price: "54 999 ₽",
    gz: "120 Гц",
    diagonal: "6,2",
    wirelessСharging: true,
    memory: "128 Гб",
  },
  {
    id: 5,
    name: "Realme 8 pro",
    image: require("../images/realme.png"),
    year: "2021",
    made: "Китай",
    brand: "Realme",
    nfc: true,
    eSim: false,
    price: "23 999 ₽",
    gz: "60 Гц",
    diagonal: "6,4",
    wirelessСharging: false,
    memory: "128 Гб",
  },
];
