export const dataDevices = [
  {
    name: "Apple iPhone 12",
    image: require("../images/apple12.svg"),
    year: "2020",
    made: "Китай",
    brand: "Apple",
    nfc: true,
    eSim: true,
    price: 81990,
    gz: "60 Гц",
    diagonal: "6,1",
    wirelessСharging: true,
  },
  {
    name: "Apple iPhone XR",
    image: require("../images/appleXR.svg"),
    year: "2018",
    made: "Китай",
    brand: "Apple",
    nfc: true,
    eSim: true,
    price: 47999,
    gz: "60 Гц",
    diagonal: "6,1",
    wirelessСharging: true,
  },
  {
    name: "Xiaomi Mi 11 Lite",
    image: require("../images/apple12.svg"),
    year: "2021",
    made: "Китай",
    brand: "Xiaomi",
    nfc: true,
    eSim: true,
    price: 27490,
    gz: "90 Гц",
    diagonal: "6,55",
    wirelessСharging: false,
  },
  {
    name: "Samsung Galaxy A72",
    image: require("../images/A72.svg"),
    year: "2020",
    made: "Вьетнам",
    brand: "Samsung",
    nfc: true,
    eSim: false,
    price: 32890,
    gz: "90 Гц",
    diagonal: "6,7",
    wirelessСharging: true,
  },
  {
    name: "Samsung Galaxy S21",
    image: require("../images/s21.svg"),
    year: "2021",
    made: "Китай",
    brand: "Samsung",
    nfc: true,
    eSim: true,
    price: 54999,
    gz: "120 Гц",
    diagonal: "6,2",
    wirelessСharging: true,
  },
  {
    name: "Realme 8 pro",
    image: require("../images/realme.svg"),
    year: "2021",
    made: "Китай",
    brand: "Realme",
    nfc: true,
    eSim: false,
    price: 23999,
    gz: "60 Гц",
    diagonal: "6,4",
    wirelessСharging: false,
  },
];
